name: Get VMA

on:
  workflow_dispatch:
  schedule:
    - cron: "3 * * * *"
    - cron: "8 * * * *"
    - cron: "13 * * * *"
    - cron: "18 * * * *"
    - cron: "23 * * * *"
    - cron: "28 * * * *"
    - cron: "33 * * * *"
    - cron: "38 * * * *"
    - cron: "43 * * * *"
    - cron: "48 * * * *"
    - cron: "53 * * * *"
    - cron: "58 * * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  get-vma:
    name: Get VMA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{secrets.GH_PAT}}

      - name: Get VMA
        run: ./scripts/get-vma.sh

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --staged
          git diff --staged --quiet || git commit -m "chore(data): Update VMA data"
          git push
